"use client";

import type { ThemeData } from "./theme-types";

type Variant = "developer" | "modern" | "corporate" | "ai";
type RecordValue = Record<string, string | boolean | string[] | undefined>;
const isRecord = (value: unknown): value is RecordValue => typeof value === "object" && value !== null && !Array.isArray(value);
const text = (value: unknown) => typeof value === "string" ? value : "";
const list = (value: unknown): unknown[] => Array.isArray(value) ? value : [];
const lines = (value: unknown): string[] => Array.isArray(value) ? value.filter((v): v is string => typeof v === "string") : text(value) ? [text(value)] : [];
const skillName = (value: unknown) => typeof value === "string" ? value : isRecord(value) ? text(value.name) : "";
const sectionClass: Record<Variant, string> = { developer: "border-zinc-800 bg-zinc-950", modern: "border-zinc-200 bg-white", corporate: "border-slate-200 bg-slate-50", ai: "border-cyan-500/20 bg-zinc-950/80" };
const mutedClass: Record<Variant, string> = { developer: "text-zinc-400", modern: "text-zinc-600", corporate: "text-slate-600", ai: "text-zinc-300" };
const accentClass: Record<Variant, string> = { developer: "text-cyan-400", modern: "text-indigo-600", corporate: "text-slate-700", ai: "text-cyan-400" };

function Section({ variant, label, children }: { variant: Variant; label: string; children: React.ReactNode }) {
  return <section className={`rounded-2xl border p-6 ${sectionClass[variant]}`}><p className={`font-mono text-xs uppercase tracking-[0.25em] ${accentClass[variant]}`}>{label}</p><div className="mt-5">{children}</div></section>;
}

export default function CompleteThemeSections({ data, variant }: { data: ThemeData; variant: Variant }) {
  const items = (key: keyof ThemeData) => list(data[key]);
  const experience = items("experience"); const projects = items("projects"); const education = items("education"); const certifications = items("certifications"); const achievements = items("achievements"); const links = items("socialLinks");
  const skills = items("skills").map(skillName).filter(Boolean);
  const hasPersonal = Boolean(data.personalInfo || data.personal);
  const profile = data.professionalProfile ?? {};
  const hasProfile = Boolean(profile && (profile.title || profile.domain || profile.seniority || profile.specializations?.length || profile.evidence?.length));
  return <div className="mx-auto max-w-6xl space-y-6 px-6 pb-20">
    {hasPersonal && <Section variant={variant} label={variant === "ai" ? "CONTACT_INTERFACE" : "Contact"}><div className={`grid gap-3 sm:grid-cols-2 ${mutedClass[variant]}`}>{(["email", "phone", "location", "website"] as const).map(key => { const value = text(data.personalInfo?.[key]) || text(data.personal?.[key]); if (!value) return null; return key === "email" || key === "phone" || key === "website" ? <a key={key} href={key === "email" ? `mailto:${value}` : key === "phone" ? `tel:${value}` : value} target={key === "website" ? "_blank" : undefined} rel={key === "website" ? "noreferrer" : undefined} className={accentClass[variant]}>{key}: {value}</a> : <span key={key}>{key}: {value}</span>; })}</div></Section>}
    {hasProfile && <Section variant={variant} label={variant === "ai" ? "PROFESSIONAL_PROFILE" : "Professional Profile"}><div className={mutedClass[variant]}><p className={`text-xl font-semibold ${accentClass[variant]}`}>{profile?.title}</p><p>{profile?.domain} {profile?.seniority && `· ${profile.seniority}`}</p><div className="mt-3 flex flex-wrap gap-2">{list(profile?.specializations).map((v, i) => <span key={`${text(v)}-${i}`} className="rounded-full border px-3 py-1 text-sm">{text(v)}</span>)}</div>{list(profile?.evidence).length > 0 && <ul className="mt-4 list-disc pl-5">{list(profile.evidence).map((v, i) => <li key={`${text(v)}-${i}`}>{text(v)}</li>)}</ul>}</div></Section>}
    {text(data.summary) && <Section variant={variant} label={variant === "ai" ? "PROFILE_SUMMARY" : "Summary"}><p className={`leading-8 ${mutedClass[variant]}`}>{data.summary}</p></Section>}
    {skills.length > 0 && <Section variant={variant} label={variant === "ai" ? "SKILL_MATRIX" : "Skills"}><div className="flex flex-wrap gap-3">{skills.map((skill, i) => <span key={`${skill}-${i}`} className={`rounded-full border px-4 py-2 ${accentClass[variant]}`}>{skill}</span>)}</div></Section>}
    {experience.length > 0 && <Section variant={variant} label={variant === "ai" ? "EXPERIENCE" : "Experience"}><div className="space-y-6">{experience.map((value, i) => { const item = isRecord(value) ? value : {}; const description = lines(item.description); return <article key={i}><h3 className={`text-xl font-semibold ${accentClass[variant]}`}>{text(item.role) || text(item.title)}</h3><p className={mutedClass[variant]}>{text(item.company)}{text(item.location) && ` · ${text(item.location)}`}</p><p className={`text-sm ${mutedClass[variant]}`}>{text(item.startDate)}{(item.startDate || item.endDate) && " — "}{item.current === true ? "Present" : text(item.endDate)}</p>{description.length > 0 && <ul className={`mt-3 list-disc space-y-1 pl-5 ${mutedClass[variant]}`}>{description.map((line, j) => <li key={j}>{line}</li>)}</ul>}</article>; })}</div></Section>}
    {projects.length > 0 && <Section variant={variant} label={variant === "ai" ? "PROJECTS" : "Projects"}><div className="grid gap-5 md:grid-cols-2">{projects.map((value, i) => { const item = isRecord(value) ? value : {}; const description = lines(item.description); return <article key={i}><h3 className="text-xl font-semibold">{text(item.title) || text(item.name)}</h3>{description.map((line, j) => <p key={j} className={`mt-2 ${mutedClass[variant]}`}>{line}</p>)}<div className="mt-3 flex flex-wrap gap-2">{list(item.technologies).map((tech, j) => <span key={j} className="rounded bg-black/10 px-2 py-1 text-xs">{text(tech)}</span>)}</div><div className="mt-4 flex gap-4">{([["githubUrl", "GitHub"], ["liveUrl", "Live Demo"], ["url", "View"]] as const).map(([key, label]) => text(item[key]) && <a key={key} href={text(item[key])} target="_blank" rel="noreferrer" className={accentClass[variant]}>{label} ↗</a>)}</div></article>; })}</div></Section>}
    {education.length > 0 && <Section variant={variant} label={variant === "ai" ? "EDUCATION" : "Education"}><div className="space-y-4">{education.map((value, i) => { const item = isRecord(value) ? value : {}; return <article key={i}><h3 className="font-semibold">{text(item.degree)}</h3><p className={accentClass[variant]}>{text(item.institution)}</p><p className={mutedClass[variant]}>{text(item.fieldOfStudy)}{(item.startYear || item.endYear) && ` · ${text(item.startYear)} — ${text(item.endYear)}`}{text(item.grade) && ` · Grade: ${text(item.grade)}`}</p></article>; })}</div></Section>}
    {certifications.length > 0 && <Section variant={variant} label={variant === "ai" ? "CERTIFICATIONS" : "Certifications"}><div className="space-y-3">{certifications.map((value, i) => { const item = isRecord(value) ? value : {}; const name = typeof value === "string" ? value : text(item.name); return <article key={i}><p className={`font-semibold ${accentClass[variant]}`}>{name}</p><p className={mutedClass[variant]}>{text(item.issuer)} {text(item.issueDate)}</p>{text(item.credentialUrl) && <a href={text(item.credentialUrl)} target="_blank" rel="noreferrer" className={accentClass[variant]}>Credential ↗</a>}</article>; })}</div></Section>}
    {achievements.length > 0 && <Section variant={variant} label={variant === "ai" ? "ACHIEVEMENTS" : "Achievements"}><div className="space-y-3">{achievements.map((value, i) => { const item = isRecord(value) ? value : {}; return <article key={i}><p className="font-semibold">{typeof value === "string" ? value : text(item.title)}</p><p className={mutedClass[variant]}>{text(item.description)} {text(item.date)}</p></article>; })}</div></Section>}
    {items("languages").length > 0 && <Section variant={variant} label={variant === "ai" ? "LANGUAGES" : "Languages"}><p className={mutedClass[variant]}>{items("languages").map(text).filter(Boolean).join(" · ")}</p></Section>}
    {items("interests").length > 0 && <Section variant={variant} label={variant === "ai" ? "INTERESTS" : "Interests"}><p className={mutedClass[variant]}>{items("interests").map(text).filter(Boolean).join(" · ")}</p></Section>}
    {links.length > 0 && <Section variant={variant} label={variant === "ai" ? "CONNECT" : "Social Links"}><div className="flex flex-wrap gap-4">{links.map((value, i) => { const item = isRecord(value) ? value : {}; return text(item.url) && <a key={i} href={text(item.url)} target="_blank" rel="noreferrer" className={accentClass[variant]}>{text(item.platform) || text(item.url)} ↗</a>; })}</div></Section>}
  </div>;
}
