"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";
import type { PortfolioData } from "@/types/portfolio";
import PortfolioRenderer from "@/components/portfolio/PortfolioRenderer";
import type { ThemeData } from "@/components/portfolio/themes/theme-types";

type ApiResult = { success?: boolean; error?: string; portfolio?: { slug: string; template: string; published: boolean; data: PortfolioData } };
async function parseApiResponse(response: Response): Promise<ApiResult> {
  const text = await response.text();
  if (!text) throw new Error(`Server returned an empty response (${response.status})`);
  try { return JSON.parse(text) as ApiResult; } catch { throw new Error(`Server returned invalid JSON (${response.status}): ${text.slice(0, 300)}`); }
}
const sections: Array<keyof PortfolioData> = ["skills", "experience", "projects", "education", "certifications", "achievements", "languages", "interests", "socialLinks"];
export default function PortfolioEditorPage() {
  const { id } = useParams<{ id: string }>();
  const [data, setData] = useState<PortfolioData | null>(null); const [slug, setSlug] = useState(""); const [template, setTemplate] = useState("developer"); const [published, setPublished] = useState(false);
  const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [publishing, setPublishing] = useState(false); const [message, setMessage] = useState(""); const [previewOpen, setPreviewOpen] = useState(false); const [copied, setCopied] = useState(false);
  useEffect(() => { if (!id) return; void (async () => { try { const result = await parseApiResponse(await fetch(`/api/portfolio/${id}`)); if (!result.portfolio) throw new Error(result.error || "Portfolio not found."); setData(result.portfolio.data); setSlug(result.portfolio.slug); setTemplate(result.portfolio.template || "developer"); setPublished(result.portfolio.published); } catch (error) { setMessage(error instanceof Error ? error.message : "Failed to load portfolio."); } finally { setLoading(false); } })(); }, [id]);
  const update = (section: keyof PortfolioData, value: unknown) => setData(current => current ? { ...current, [section]: value } : current);
  const updateNested = (section: "personalInfo" | "professionalProfile", field: string, value: string) => setData(current => current ? { ...current, [section]: { ...current[section], [field]: value } } : current);
  async function save(nextPublished = published) { if (!data) return false; setSaving(true); setMessage(""); try { const result = await parseApiResponse(await fetch(`/api/portfolio/${id}`, { method: "PUT", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ data, template, published: nextPublished }) })); if (!result.success) throw new Error(result.error || "Failed to save portfolio."); setPublished(nextPublished); setMessage("Portfolio saved successfully."); return true; } catch (error) { setMessage(error instanceof Error ? error.message : "Failed to save portfolio."); return false; } finally { setSaving(false); } }
  async function togglePublish() { const nextPublished = !published; setPublishing(true); const success = await save(nextPublished); if (success) setMessage(nextPublished ? "Portfolio published! Your portfolio is now live." : "Portfolio unpublished."); setPublishing(false); }
  async function copyLink() { await navigator.clipboard.writeText(`${window.location.origin}/portfolio/${slug}`); setCopied(true); window.setTimeout(() => setCopied(false), 1600); }
  if (loading) return <main className="min-h-screen bg-black p-8 text-white">Loading portfolio...</main>;
  if (!data) return <main className="min-h-screen bg-black p-8 text-red-400">{message || "Portfolio could not be loaded."}</main>;
  const input = "mt-2 w-full rounded-xl border border-zinc-700 bg-black px-4 py-3 text-white outline-none focus:border-cyan-400";
  return <main className="min-h-screen bg-black text-white"><div className="mx-auto max-w-6xl px-6 py-10"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-cyan-400">ResumeForge</p><h1 className="mt-2 text-4xl font-bold">Edit Portfolio</h1><span className={`mt-3 inline-flex items-center gap-2 rounded-full border px-3 py-1 text-xs ${published ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-300" : "border-amber-500/30 bg-amber-500/10 text-amber-300"}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{published ? "Published" : "Draft"}</span></div><div className="flex flex-wrap gap-3"><button className="rounded-xl border border-zinc-700 px-5 py-3 transition hover:border-cyan-400/50" onClick={() => setPreviewOpen(true)}>Preview</button><button className="rounded-xl bg-cyan-500 px-5 py-3 font-semibold text-black disabled:opacity-50" disabled={saving || publishing} onClick={() => void save()}>{saving ? "Saving..." : "Save Changes"}</button><button className={`rounded-xl px-5 py-3 font-semibold transition disabled:opacity-50 ${published ? "border border-amber-400/40 bg-amber-400/10 text-amber-300 hover:bg-amber-400/20" : "bg-emerald-400 text-black hover:bg-emerald-300"}`} disabled={saving || publishing} onClick={() => void togglePublish()}>{publishing ? "Updating..." : published ? "Unpublish" : "Publish Portfolio"}</button></div></div>{message && <p className={`mt-6 rounded-xl border p-4 text-sm ${message.includes("published") && !message.includes("unpublished") ? "border-emerald-400/30 bg-emerald-400/10 text-emerald-300" : "border-zinc-800 text-zinc-300"}`}>{message}</p>}{published && <div className="mt-4 rounded-2xl border border-emerald-400/20 bg-emerald-400/5 p-5"><p className="font-semibold text-emerald-300">✓ Portfolio published!</p><p className="mt-1 text-sm text-zinc-400">Your portfolio is now live.</p><p className="mt-3 break-all font-mono text-xs text-zinc-500">{typeof window === "undefined" ? "" : `${window.location.origin}/portfolio/${slug}`}</p><div className="mt-4 flex flex-wrap gap-3"><button type="button" onClick={() => void copyLink()} className="rounded-lg border border-emerald-400/30 px-4 py-2 text-sm text-emerald-300">{copied ? "Copied!" : "Copy Link"}</button><a href={`/portfolio/${slug}`} target="_blank" rel="noreferrer" className="rounded-lg bg-emerald-400 px-4 py-2 text-sm font-semibold text-black">Open Portfolio</a></div></div>}
    {previewOpen && <div className="fixed inset-0 z-50 overflow-y-auto bg-black/80 p-4 backdrop-blur-sm"><div className="mx-auto max-w-6xl rounded-2xl border border-zinc-700 bg-black shadow-2xl"><div className="flex items-center justify-between border-b border-zinc-800 p-4"><div><p className="font-semibold">Portfolio Preview</p><p className="text-xs text-zinc-500">Draft preview is visible only to you.</p></div><button type="button" onClick={() => setPreviewOpen(false)} className="rounded-lg border border-zinc-700 px-3 py-2 text-sm text-zinc-300">Close</button></div><PortfolioRenderer template={template} data={data as unknown as ThemeData} /></div></div>}
    <section className="mt-8 rounded-2xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-xl font-semibold">Portfolio Theme</h2><select className={input+" md:w-96"} value={template} onChange={e => setTemplate(e.target.value)}><option value="developer">Developer</option><option value="modern">Modern</option><option value="corporate">Corporate</option><option value="ai">AI Neon</option></select></section>
    <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-xl font-semibold">Personal Information</h2><div className="mt-5 grid gap-4 md:grid-cols-2">{(["fullName","email","phone","location","website"] as const).map(field => <label key={field} className="text-sm text-zinc-400">{field}<input className={input} value={data.personalInfo?.[field] || ""} onChange={e => updateNested("personalInfo", field, e.target.value)} /></label>)}</div></section>
    <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-xl font-semibold">Professional Profile</h2><div className="mt-5 grid gap-4 md:grid-cols-3">{(["title","domain","seniority"] as const).map(field => <label key={field} className="text-sm text-zinc-400">{field}<input className={input} value={data.professionalProfile?.[field] || ""} onChange={e => updateNested("professionalProfile", field, e.target.value)} /></label>)}</div></section>
    <section className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-xl font-semibold">Summary</h2><textarea className={input} rows={6} value={data.summary || ""} onChange={e => update("summary", e.target.value)} /></section>
    {sections.map(section => <section key={section} className="mt-6 rounded-2xl border border-zinc-800 bg-zinc-950 p-6"><h2 className="text-xl font-semibold capitalize">{section}</h2><textarea className={input+" mt-5 font-mono text-sm"} rows={Math.min(18, Math.max(5, JSON.stringify(data[section], null, 2).split("\n").length))} value={JSON.stringify(data[section], null, 2)} onChange={e => { try { update(section, JSON.parse(e.target.value) as PortfolioData[typeof section]); } catch { /* Keep the current value until valid JSON is entered. */ } }} /></section>)}
    <button className="mt-8 rounded-xl bg-cyan-500 px-8 py-4 font-semibold text-black" disabled={saving} onClick={() => void save()}>{saving ? "Saving..." : "Save Portfolio"}</button></div></main>;
}
